# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_gateway_route.howto-k8s-ingress-gateway__ingress-gw_howto-k8s-ingress-gateway__gateway-route-paths_howto-k8s-ingress-gateway:
resource "aws_appmesh_gateway_route" "howto-k8s-ingress-gateway__ingress-gw_howto-k8s-ingress-gateway__gateway-route-paths_howto-k8s-ingress-gateway" {
  mesh_name            = "howto-k8s-ingress-gateway"
  mesh_owner           = "566972129213"
  name                 = "gateway-route-paths_howto-k8s-ingress-gateway"
  tags                 = {}
  virtual_gateway_name = "ingress-gw_howto-k8s-ingress-gateway"

  spec {

    http_route {
      action {
        target {
          virtual_service {
            virtual_service_name = "color-paths.howto-k8s-ingress-gateway.svc.cluster.local"
          }
        }
      }

      match {
        prefix = "/paths"
      }
    }
  }
}
