# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_virtual_gateway.howto-k8s-ingress-gateway__ingress-gw_howto-k8s-ingress-gateway:
resource "aws_appmesh_virtual_gateway" "howto-k8s-ingress-gateway__ingress-gw_howto-k8s-ingress-gateway" {
  mesh_name  = "howto-k8s-ingress-gateway"
  mesh_owner = "566972129213"
  name       = "ingress-gw_howto-k8s-ingress-gateway"
  tags       = {}

  spec {

    listener {

      port_mapping {
        port     = 8088
        protocol = "http"
      }
    }
  }
}
