# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_mesh.howto-k8s-ingress-gateway:
resource "aws_appmesh_mesh" "howto-k8s-ingress-gateway" {
  name = "howto-k8s-ingress-gateway"
  tags = {}

  spec {
  }
}
