# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eks_cluster.cluster:

data "aws_subnet_ids" "private" {
  vpc_id = data.terraform_remote_state.net.outputs.eks-vpc
  tags = {
    "subnet-type" = "private"
  }
}


resource "aws_eks_cluster" "cluster" {
  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler",
  ]
  name = var.cluster-name

  role_arn = data.terraform_remote_state.iam.outputs.cluster_service_role_arn
  tags     = {}
  version  = var.eks_version

  timeouts {}

  vpc_config {
    endpoint_private_access = true
    endpoint_public_access  = false
    public_access_cidrs = [
      "0.0.0.0/0",
    ]
    security_group_ids = [
      data.terraform_remote_state.net.outputs.cluster-sg,
    ]
    subnet_ids = concat(sort(data.aws_subnet_ids.private.ids))
  }

  encryption_config {
    provider {
      key_arn = data.aws_kms_key.ekskey.arn
    }
    resources = ["secrets"]
  }

  provisioner "local-exec" {
    command     = "until curl --output /dev/null --insecure --silent ${self.endpoint}/healthz; do sleep 1; done"
    working_dir = path.module
  }


}

resource "aws_cloudwatch_log_group" "cluster" {
  name              = format("/aws/eks/%s-%s/cluster", var.cluster-name, var.tfid)
  retention_in_days = var.log_retention
}