apiVersion: v1
kind: Service
metadata:
  name: karpenter-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | indent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
  selector:
    karpenter: webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      karpenter: webhook
  template:
    metadata:
      labels:
        karpenter: webhook
        {{- include "karpenter.labels" . | indent 8 }}
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ template "karpenter.serviceAccountName" . }}
      containers:
        - name: webhook
          image: {{ .Values.webhook.image }}
          args:
            - -port={{ .Values.webhook.port }}
        {{- if .Values.webhook.resources }}
          resources: {{ toYaml .Values.webhook.resources | nindent 12 }}
        {{- end }}
          ports:
            - name: webhook
              containerPort: {{ .Values.webhook.port }}
          livenessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ .Values.webhook.port }}
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: {{ .Values.webhook.port }}
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.controller.clusterName }}
            - name: CLUSTER_ENDPOINT
              value: {{ .Values.controller.clusterEndpoint }}
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.aws.defaultInstanceProfile }}
            - name: AWS_DEFAULT_INSTANCE_PROFILE
              value: {{ .Values.aws.defaultInstanceProfile }}
            {{- end }}
          {{- with .Values.webhook.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      # https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8#issuecomment-636888074 - not needed in k8s versions 1.19+
      securityContext:
        fsGroup: 1000
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.webhook.affinity }}
          {{- toYaml .Values.webhook.affinity | nindent 8 }}
        {{- else }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
        {{- end }}
      {{- if .Values.webhook.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: karpenter-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | indent 4 }}
data: {} # Injected by karpenter-webhook
