apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: fargate1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 566972129213.dkr.ecr.eu-west-1.amazonaws.com/nginx:latest
          ports:
            - name: http
              containerPort: 80
