# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.eksctl-ateksf1-cluster-FargatePodExecutionRole-86R6T0RQZPHM:
resource "aws_iam_role" "FargatePodExecutionRole" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = [
              "eks.amazonaws.com",
              "eks-fargate-pods.amazonaws.com",
            ]
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  max_session_duration  = 3600
  name                  = "FargatePodExecutionRole"
  path                  = "/"
  tags = {
    "Name" = "ateksf1-cluster/FargatePodExecutionRole"
  }
}
