# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_appmesh_route.howto-k8s-ingress-gateway__color-paths_howto-k8s-ingress-gateway__color-route-red:
resource "aws_appmesh_route" "howto-k8s-ingress-gateway__color-paths_howto-k8s-ingress-gateway__color-route-red" {
  mesh_name           = "howto-k8s-ingress-gateway"
  mesh_owner          = data.aws_caller_identity.current.account_id
  name                = "color-route-red"
  tags                = {}
  virtual_router_name = "color-paths_howto-k8s-ingress-gateway"

  spec {
    priority = 30

    http_route {
      action {
        weighted_target {
          virtual_node = "red_howto-k8s-ingress-gateway"
          weight       = 1
        }
      }

      match {
        prefix = "/red"
      }
    }
  }
}
